(use-package yaml-mode :ensure t)
;; (use-package highlight-indentation :ensure t)
;; (setq highlight-indentation-offset 2)
;; (set-face-background 'highlight-indentation-face "#191970")
;; (set-face-background 'highlight-indentation-current-column-face "#2f4f4f")
;; (add-hook 'yaml-mode-hook 'highlight-indentation-mode)
;; (add-hook 'yaml-mode-hook 'highlight-indentation-current-column-mode)
;; (add-hook 'yaml-mode-hook '(lambda() (setq highlight-indentation-offset 2)))
